### ISSUE TITLE
Update requirements

### ISSUE THREAD

**Issue by bknueven** [mpi-sppy/mpi-sppy#52]
Check and update both the requirements.txt file (which has some fixed values for scipy and numpy), as well as `install_requires` in setup.py

mpi-sppy needs at least Pyomo 5.7.0 for `LShaped` (`RelaxIntegerVars`) and at least Pyomo 5.7.1 for good performance of FWPH with persistent solvers.

**Comment by dtmildebrath** [comment]
A few thoughts:
- It looks like the only use of scipy in the entire code is a single call to the CDF of the standard normal distribution in `ccopf_multistage.py`. Is this script still "active"? If so, we can accept virtually any version of scipy, as this functionality is extremely basic.
- I think we can just require `pyomo>=5.7.1` in the requirements.txt. Is there a reason not to do this?
- Here is a list of every single Numpy object, function, etc. that we use. None of them seem suspect; I think we can require `numpy>=1.16`, as this is the last version to support python 2.7 (which we don't) and has support expiring in 2020 ([see here](https://numpy.org/doc/stable/release/1.16.0-notes.html)).

> 
> - np.abs
> - np.arange
> - np.array
> - np.array_equal
> - np.copyto
> - np.empty
> - np.empty_like
> - np.fromiter
> - np.full_like
> - np.inf
> - np.int64
> - np.linalg.norm
> - np.loadtxt
> - np.max
> - np.maximum
> - np.mean
> - np.min
> - np.minimum
> - np.nan
> - np.ndarray
> - np.ones
> - np.power
> - np.random.RandomState
> - np.random.normal
> - np.random.rand
> - np.random.uniform
> - np.reshape
> - np.sort
> - np.sqrt
> - np.where
> - np.zeros

**Comment by bknueven** [comment]
I'm in favor of requiring `pyomo>=5.7.1`. We could also eliminate some hack-ish code [in FWPH](https://github.com/mpi-sppy/mpi-sppy/blob/c61282d96df46103709fa11d18910c102235a12e/mpisppy/fwph/fwph.py#L315), which is purely for older versions of Pyomo.

Given that this is new software, I don't think we should lock ourselves into bending over backwards for older versions of libraries. I would propose we require `numpy>=1.19` and `scipy>=1.5` to give us more flexibility in future development.

**Comment by bknueven** [comment]
To be complete, for similar reasons I think we should require `mpi4py>=3.0.3` and `pyutilib>=6.0` (the later should come for free with `pyomo>=5.7.1`).

**Comment by dtmildebrath** [comment]
I apparently do not have appropriate permissions to link PRs and issues, but I just opened #72
